"""prima migrazione2

Revision ID: 2e6a6522e4f7
Revises: 
Create Date: 2025-09-19 17:25:14.178958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6a6522e4f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rilevazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citta', sa.String(), nullable=False),
    sa.Column('tempo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rilevazioni')
    # ### end Alembic commands ###
